spring.application.name=devdevgo-jobs-service
server.port=8080

# Adzuna API
adzuna.base-url=https://api.adzuna.com/v1/api
adzuna.app-id=${ADZUNA_APP_ID}
adzuna.app-key=${ADZUNA_APP_KEY}
adzuna.country=in
adzuna.default-results-per-page=10

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logs
logging.level.com.devdevgo.jobs=INFO